# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duid', models.CharField(max_length=258, verbose_name='DUID')),
                ('interface_id', models.CharField(blank=True, max_length=256, verbose_name='Interface-ID')),
                ('remote_id', models.CharField(blank=True, max_length=512, verbose_name='Remote-ID')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ('remote_id', 'interface_id', 'duid'),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_request_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='last request type')),
                ('last_request', models.TextField(blank=True, null=True, verbose_name='last request')),
                ('last_request_ll', models.GenericIPAddressField(blank=True, null=True, protocol='ipv6', verbose_name='Link-local address')),
                ('last_request_ts', models.DateTimeField(blank=True, null=True, verbose_name='last request timestamp')),
                ('last_response_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='last response type')),
                ('last_response', models.TextField(blank=True, null=True, verbose_name='last response')),
                ('last_response_ts', models.DateTimeField(blank=True, null=True, verbose_name='last response timestamp')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhcpkit_looking_glass.Client')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhcpkit_looking_glass.Server')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ('client', 'server'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set([('duid', 'interface_id', 'remote_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('client', 'server')]),
        ),
    ]
