# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpkit_looking_glass', '0002_auto_20151110_0017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Transaction',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
